# Generated by Django 3.1.1 on 2020-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField()),
                ('short_url', models.URLField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('used_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ссылки',
                'verbose_name_plural': 'Ссылка',
            },
        ),
    ]
